// <auto-generated />
using System;
using CuMusicClub.Domain.Enums;
using CuMusicClub.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CuMusicClub.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260906105506_ReplaceIdentityWithCustomUserRepo")]
    partial class ReplaceIdentityWithCustomUserRepo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "song_link_type", new[] { "youtube", "yandex_music", "soundcloud" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CuMusicClub.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("AvatarUrl");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DisplayName");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("Email");

                    b.Property<bool>("IsChatMember")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsChatMember");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("PasswordHash");

                    b.Property<long?>("TgUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("TgUserId");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("UserName");

                    b.HasKey("Id");

                    b.HasIndex("TgUserId")
                        .IsUnique()
                        .HasDatabaseName("idx_application_user_tg_user_id");

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.Calendar", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("CalendarUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("calendar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("UserId");

                    b.ToTable("calendar", (string)null);
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.CalendarAttachState", b =>
                {
                    b.Property<long>("TgUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("tg_user_id");

                    b.Property<string>("PendingEmail")
                        .HasColumnType("text")
                        .HasColumnName("pending_email");

                    b.Property<Guid?>("PendingUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("pending_user_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("TgUserId");

                    b.ToTable("calendar_attach_state", (string)null);
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.DataEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasComment("полезная информация");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("этому нельзя доверять, но мы будем");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasComment("дедубликация");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasComment("опциональная метаинфа");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.ToTable("data_entry", null, t =>
                        {
                            t.HasComment("айноды с каким-то содержанием. жалкая замена s3 ибо мне лень инфру настраивать");
                        });
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<bool>("NotifyDayBefore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("notify_day_before");

                    b.Property<bool>("NotifyHourBefore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("notify_hour_before");

                    b.Property<DateTimeOffset?>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("StartAt")
                        .HasDatabaseName("idx_event_start_at");

                    b.ToTable("event", (string)null);
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.EventParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid?>("TrackItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_item_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("idx_event_participant_event");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_event_participant_user");

                    b.HasIndex("EventId", "TrackItemId");

                    b.HasIndex("EventId", "Role", "UserId", "TrackItemId")
                        .IsUnique()
                        .HasDatabaseName("uniq_event_participation");

                    b.ToTable("event_participant", (string)null);
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.EventTrackItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CustomArtist")
                        .HasColumnType("text")
                        .HasColumnName("custom_artist");

                    b.Property<string>("CustomTitle")
                        .HasColumnType("text")
                        .HasColumnName("custom_title");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid?>("SongId")
                        .HasColumnType("uuid")
                        .HasColumnName("song_id");

                    b.HasKey("Id");

                    b.HasAlternateKey("EventId", "Id")
                        .HasName("track_item_identity");

                    b.HasIndex("SongId");

                    b.HasIndex("EventId", "Position")
                        .IsUnique()
                        .HasDatabaseName("track_item_position");

                    b.ToTable("event_track_item", null, t =>
                        {
                            t.HasCheckConstraint("track_item_requires_title", "\"song_id\" IS NOT NULL OR \"custom_title\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Jti")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("jti")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("Exp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exp")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset>("Iat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("iat")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<Guid>("Sub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("sub")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.HasKey("Jti");

                    b.HasIndex("Exp")
                        .HasDatabaseName("idx_refresh_token_exp");

                    b.HasIndex("Iat")
                        .HasDatabaseName("idx_refresh_token_iat");

                    b.HasIndex("Revoked")
                        .HasDatabaseName("idx_refresh_token_revoked");

                    b.HasIndex("Sub")
                        .HasDatabaseName("idx_refresh_token_sub");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.RoleTitle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Svg")
                        .HasColumnType("text")
                        .HasColumnName("svg")
                        .HasComment("Именно вот HTML записанный svg иконки, изображающей роль");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasDatabaseName("idx_role_title_unique_title");

                    b.ToTable("role_title", (string)null);
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("artist");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_featured");

                    b.Property<SongLinkType>("LinkKind")
                        .HasColumnType("song_link_type")
                        .HasColumnName("link_kind");

                    b.Property<string>("LinkUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("link_url");

                    b.Property<Guid?>("ThumbnailDataEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("thumbnail_data_entry_id");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url")
                        .HasComment("DEPRECATED: SHOULD BE READONLY. USE thumbnail_data_entry_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ThumbnailDataEntryId");

                    b.ToTable("song", (string)null);
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.SongRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uuid")
                        .HasColumnName("song_id");

                    b.HasKey("Id");

                    b.HasIndex("SongId", "RoleTitle")
                        .IsUnique()
                        .HasDatabaseName("song_role_song_id_role_title_unique");

                    b.ToTable("song_role", (string)null);
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.SongRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uuid")
                        .HasColumnName("song_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId")
                        .IsUnique();

                    b.HasIndex("SongId")
                        .HasDatabaseName("idx_song_role_assignment_song");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_song_role_assignment_user");

                    b.HasIndex("SongId", "RoleId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("song_role_assignment_unique");

                    b.ToTable("song_role_assignment", (string)null);
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.SongTopic", b =>
                {
                    b.Property<long>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("topic_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TopicId"));

                    b.Property<long?>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uuid")
                        .HasColumnName("song_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("TopicId");

                    b.HasIndex("SongId")
                        .IsUnique()
                        .HasDatabaseName("idx_song_topic_song_id");

                    b.ToTable("song_topic", (string)null);
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.SongTopicMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("TopicId")
                        .HasColumnType("bigint")
                        .HasColumnName("topic_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.HasIndex("UserId");

                    b.ToTable("song_topic_member", (string)null);
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.TgAuthLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<long?>("TgUserId")
                        .HasColumnType("bigint")
                        .HasComment("Айди кто использовал ссылку");

                    b.HasKey("Id");

                    b.HasIndex("TgUserId");

                    b.ToTable("tg_auth_link", null, t =>
                        {
                            t.HasComment("Диплинки для захода в систему");
                        });
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.UserPermission", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.Property<string>("Permission")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Permission");

                    b.HasKey("UserId", "Permission");

                    b.ToTable("user_permissions", (string)null);
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.UserPreferences", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("AllowAdding")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("allow_adding");

                    b.Property<bool>("AllowRemoving")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("allow_removing");

                    b.HasKey("UserId");

                    b.ToTable("user_preferences", (string)null);
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("RefreshTokenJti")
                        .HasColumnType("uuid");

                    b.Property<string>("ScreenResolution")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("screen_resolution");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RefreshTokenJti")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_user_session_user_id");

                    b.ToTable("user_session", (string)null);
                });

            modelBuilder.Entity("UserRolePreference", b =>
                {
                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<long>("PreferredRoleId")
                        .HasColumnType("bigint");

                    b.HasKey("ApplicationUserId", "PreferredRoleId");

                    b.HasIndex("PreferredRoleId");

                    b.ToTable("users_preferred_roles", (string)null);
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.Calendar", b =>
                {
                    b.HasOne("CuMusicClub.Domain.Entities.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("CuMusicClub.Domain.Entities.Calendar", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.Event", b =>
                {
                    b.HasOne("CuMusicClub.Domain.Entities.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.EventParticipant", b =>
                {
                    b.HasOne("CuMusicClub.Domain.Entities.Event", "Event")
                        .WithMany("Participants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_participant_event");

                    b.HasOne("CuMusicClub.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CuMusicClub.Domain.Entities.EventTrackItem", "TrackItem")
                        .WithMany()
                        .HasForeignKey("EventId", "TrackItemId")
                        .HasPrincipalKey("EventId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_event_participant_track_item");

                    b.Navigation("Event");

                    b.Navigation("TrackItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.EventTrackItem", b =>
                {
                    b.HasOne("CuMusicClub.Domain.Entities.Event", "Event")
                        .WithMany("TrackItems")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CuMusicClub.Domain.Entities.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Event");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("CuMusicClub.Domain.Entities.ApplicationUser", "SubUser")
                        .WithMany()
                        .HasForeignKey("Sub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubUser");
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.Song", b =>
                {
                    b.HasOne("CuMusicClub.Domain.Entities.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CuMusicClub.Domain.Entities.DataEntry", "ThumbnailDataEntry")
                        .WithMany()
                        .HasForeignKey("ThumbnailDataEntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");

                    b.Navigation("ThumbnailDataEntry");
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.SongRole", b =>
                {
                    b.HasOne("CuMusicClub.Domain.Entities.Song", "Song")
                        .WithMany("Roles")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.SongRoleAssignment", b =>
                {
                    b.HasOne("CuMusicClub.Domain.Entities.SongRole", "SongRole")
                        .WithOne("Assignment")
                        .HasForeignKey("CuMusicClub.Domain.Entities.SongRoleAssignment", "RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("song_role_assignment");

                    b.HasOne("CuMusicClub.Domain.Entities.Song", "Song")
                        .WithMany("Assignments")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CuMusicClub.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");

                    b.Navigation("SongRole");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.SongTopic", b =>
                {
                    b.HasOne("CuMusicClub.Domain.Entities.Song", "Song")
                        .WithOne("SongTopic")
                        .HasForeignKey("CuMusicClub.Domain.Entities.SongTopic", "SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.SongTopicMember", b =>
                {
                    b.HasOne("CuMusicClub.Domain.Entities.SongTopic", "Topic")
                        .WithMany("TopicMembers")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CuMusicClub.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.UserPermission", b =>
                {
                    b.HasOne("CuMusicClub.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.UserPreferences", b =>
                {
                    b.HasOne("CuMusicClub.Domain.Entities.ApplicationUser", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("CuMusicClub.Domain.Entities.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("CuMusicClub.Domain.Entities.RefreshToken", "RefreshToken")
                        .WithOne("JtiSession")
                        .HasForeignKey("CuMusicClub.Domain.Entities.UserSession", "RefreshTokenJti")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CuMusicClub.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RefreshToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserRolePreference", b =>
                {
                    b.HasOne("CuMusicClub.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CuMusicClub.Domain.Entities.RoleTitle", null)
                        .WithMany()
                        .HasForeignKey("PreferredRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.Event", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("TrackItems");
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.RefreshToken", b =>
                {
                    b.Navigation("JtiSession");
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.Song", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Roles");

                    b.Navigation("SongTopic");
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.SongRole", b =>
                {
                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("CuMusicClub.Domain.Entities.SongTopic", b =>
                {
                    b.Navigation("TopicMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
