// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: auth.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Credentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *Credentials) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Credentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   *Credentials           `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	Profile       *User                  `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterUserRequest) GetCredentials() *Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *RegisterUserRequest) GetProfile() *User {
	if x != nil {
		return x.Profile
	}
	return nil
}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type TokenPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenPair) Reset() {
	*x = TokenPair{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPair) ProtoMessage() {}

func (x *TokenPair) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPair.ProtoReflect.Descriptor instead.
func (*TokenPair) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

func (x *TokenPair) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenPair) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type TgLoginLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoginLink     string                 `protobuf:"bytes,1,opt,name=login_link,json=loginLink,proto3" json:"login_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TgLoginLinkResponse) Reset() {
	*x = TgLoginLinkResponse{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TgLoginLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TgLoginLinkResponse) ProtoMessage() {}

func (x *TgLoginLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TgLoginLinkResponse.ProtoReflect.Descriptor instead.
func (*TgLoginLinkResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{4}
}

func (x *TgLoginLinkResponse) GetLoginLink() string {
	if x != nil {
		return x.LoginLink
	}
	return ""
}

type TgLoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	User  *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// Optional explicit Telegram user id (if provided by the client).
	TgUserId      uint64 `protobuf:"varint,2,opt,name=tg_user_id,json=tgUserId,proto3" json:"tg_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TgLoginRequest) Reset() {
	*x = TgLoginRequest{}
	mi := &file_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TgLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TgLoginRequest) ProtoMessage() {}

func (x *TgLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TgLoginRequest.ProtoReflect.Descriptor instead.
func (*TgLoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{5}
}

func (x *TgLoginRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *TgLoginRequest) GetTgUserId() uint64 {
	if x != nil {
		return x.TgUserId
	}
	return 0
}

type AuthSession struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JWT token pair.
	Tokens *TokenPair `protobuf:"bytes,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	// Token issued-at and expiration (unix seconds).
	Iat uint64 `protobuf:"varint,2,opt,name=iat,proto3" json:"iat,omitempty"`
	Exp uint64 `protobuf:"varint,3,opt,name=exp,proto3" json:"exp,omitempty"`
	// Whether the user is already a member of the music club chat.
	IsChatMember bool `protobuf:"varint,4,opt,name=is_chat_member,json=isChatMember,proto3" json:"is_chat_member,omitempty"`
	// If not a member, link to request manual approval to join the chat.
	JoinRequestUrl string `protobuf:"bytes,5,opt,name=join_request_url,json=joinRequestUrl,proto3" json:"join_request_url,omitempty"`
	// Convenience: current user's profile data.
	Profile *User `protobuf:"bytes,6,opt,name=profile,proto3" json:"profile,omitempty"`
	// Permissions snapshot for the session.
	Permissions   *PermissionSet `protobuf:"bytes,7,opt,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthSession) Reset() {
	*x = AuthSession{}
	mi := &file_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSession) ProtoMessage() {}

func (x *AuthSession) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSession.ProtoReflect.Descriptor instead.
func (*AuthSession) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{6}
}

func (x *AuthSession) GetTokens() *TokenPair {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *AuthSession) GetIat() uint64 {
	if x != nil {
		return x.Iat
	}
	return 0
}

func (x *AuthSession) GetExp() uint64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *AuthSession) GetIsChatMember() bool {
	if x != nil {
		return x.IsChatMember
	}
	return false
}

func (x *AuthSession) GetJoinRequestUrl() string {
	if x != nil {
		return x.JoinRequestUrl
	}
	return ""
}

func (x *AuthSession) GetProfile() *User {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *AuthSession) GetPermissions() *PermissionSet {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type ProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *User                  `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Permissions   *PermissionSet         `protobuf:"bytes,2,opt,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileResponse) Reset() {
	*x = ProfileResponse{}
	mi := &file_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileResponse) ProtoMessage() {}

func (x *ProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileResponse.ProtoReflect.Descriptor instead.
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{7}
}

func (x *ProfileResponse) GetProfile() *User {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *ProfileResponse) GetPermissions() *PermissionSet {
	if x != nil {
		return x.Permissions
	}
	return nil
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\x0emusicclub.auth\x1a\x1bgoogle/protobuf/empty.proto\x1a\x11permissions.proto\x1a\n" +
	"user.proto\"E\n" +
	"\vCredentials\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x84\x01\n" +
	"\x13RegisterUserRequest\x12=\n" +
	"\vcredentials\x18\x01 \x01(\v2\x1b.musicclub.auth.CredentialsR\vcredentials\x12.\n" +
	"\aprofile\x18\x02 \x01(\v2\x14.musicclub.user.UserR\aprofile\"5\n" +
	"\x0eRefreshRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"S\n" +
	"\tTokenPair\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"4\n" +
	"\x13TgLoginLinkResponse\x12\x1d\n" +
	"\n" +
	"login_link\x18\x01 \x01(\tR\tloginLink\"X\n" +
	"\x0eTgLoginRequest\x12(\n" +
	"\x04user\x18\x01 \x01(\v2\x14.musicclub.user.UserR\x04user\x12\x1c\n" +
	"\n" +
	"tg_user_id\x18\x02 \x01(\x04R\btgUserId\"\xac\x02\n" +
	"\vAuthSession\x121\n" +
	"\x06tokens\x18\x01 \x01(\v2\x19.musicclub.auth.TokenPairR\x06tokens\x12\x10\n" +
	"\x03iat\x18\x02 \x01(\x04R\x03iat\x12\x10\n" +
	"\x03exp\x18\x03 \x01(\x04R\x03exp\x12$\n" +
	"\x0eis_chat_member\x18\x04 \x01(\bR\fisChatMember\x12(\n" +
	"\x10join_request_url\x18\x05 \x01(\tR\x0ejoinRequestUrl\x12.\n" +
	"\aprofile\x18\x06 \x01(\v2\x14.musicclub.user.UserR\aprofile\x12F\n" +
	"\vpermissions\x18\a \x01(\v2$.musicclub.permissions.PermissionSetR\vpermissions\"\x89\x01\n" +
	"\x0fProfileResponse\x12.\n" +
	"\aprofile\x18\x01 \x01(\v2\x14.musicclub.user.UserR\aprofile\x12F\n" +
	"\vpermissions\x18\x02 \x01(\v2$.musicclub.permissions.PermissionSetR\vpermissions2\xf8\x02\n" +
	"\vAuthService\x12L\n" +
	"\bRegister\x12#.musicclub.auth.RegisterUserRequest\x1a\x1b.musicclub.auth.AuthSession\x12A\n" +
	"\x05Login\x12\x1b.musicclub.auth.Credentials\x1a\x1b.musicclub.auth.AuthSession\x12D\n" +
	"\aRefresh\x12\x1e.musicclub.auth.RefreshRequest\x1a\x19.musicclub.auth.TokenPair\x12K\n" +
	"\x0eGetTgLoginLink\x12\x14.musicclub.user.User\x1a#.musicclub.auth.TgLoginLinkResponse\x12E\n" +
	"\n" +
	"GetProfile\x12\x16.google.protobuf.Empty\x1a\x1f.musicclub.auth.ProfileResponseB\x1cZ\x1amusicclubbot/backend/protob\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_auth_proto_goTypes = []any{
	(*Credentials)(nil),         // 0: musicclub.auth.Credentials
	(*RegisterUserRequest)(nil), // 1: musicclub.auth.RegisterUserRequest
	(*RefreshRequest)(nil),      // 2: musicclub.auth.RefreshRequest
	(*TokenPair)(nil),           // 3: musicclub.auth.TokenPair
	(*TgLoginLinkResponse)(nil), // 4: musicclub.auth.TgLoginLinkResponse
	(*TgLoginRequest)(nil),      // 5: musicclub.auth.TgLoginRequest
	(*AuthSession)(nil),         // 6: musicclub.auth.AuthSession
	(*ProfileResponse)(nil),     // 7: musicclub.auth.ProfileResponse
	(*User)(nil),                // 8: musicclub.user.User
	(*PermissionSet)(nil),       // 9: musicclub.permissions.PermissionSet
	(*emptypb.Empty)(nil),       // 10: google.protobuf.Empty
}
var file_auth_proto_depIdxs = []int32{
	0,  // 0: musicclub.auth.RegisterUserRequest.credentials:type_name -> musicclub.auth.Credentials
	8,  // 1: musicclub.auth.RegisterUserRequest.profile:type_name -> musicclub.user.User
	8,  // 2: musicclub.auth.TgLoginRequest.user:type_name -> musicclub.user.User
	3,  // 3: musicclub.auth.AuthSession.tokens:type_name -> musicclub.auth.TokenPair
	8,  // 4: musicclub.auth.AuthSession.profile:type_name -> musicclub.user.User
	9,  // 5: musicclub.auth.AuthSession.permissions:type_name -> musicclub.permissions.PermissionSet
	8,  // 6: musicclub.auth.ProfileResponse.profile:type_name -> musicclub.user.User
	9,  // 7: musicclub.auth.ProfileResponse.permissions:type_name -> musicclub.permissions.PermissionSet
	1,  // 8: musicclub.auth.AuthService.Register:input_type -> musicclub.auth.RegisterUserRequest
	0,  // 9: musicclub.auth.AuthService.Login:input_type -> musicclub.auth.Credentials
	2,  // 10: musicclub.auth.AuthService.Refresh:input_type -> musicclub.auth.RefreshRequest
	8,  // 11: musicclub.auth.AuthService.GetTgLoginLink:input_type -> musicclub.user.User
	10, // 12: musicclub.auth.AuthService.GetProfile:input_type -> google.protobuf.Empty
	6,  // 13: musicclub.auth.AuthService.Register:output_type -> musicclub.auth.AuthSession
	6,  // 14: musicclub.auth.AuthService.Login:output_type -> musicclub.auth.AuthSession
	3,  // 15: musicclub.auth.AuthService.Refresh:output_type -> musicclub.auth.TokenPair
	4,  // 16: musicclub.auth.AuthService.GetTgLoginLink:output_type -> musicclub.auth.TgLoginLinkResponse
	7,  // 17: musicclub.auth.AuthService.GetProfile:output_type -> musicclub.auth.ProfileResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	file_permissions_proto_init()
	file_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
