// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: event.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventId) Reset() {
	*x = EventId{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventId) ProtoMessage() {}

func (x *EventId) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventId.ProtoReflect.Descriptor instead.
func (*EventId) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *EventId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

func (x *ListEventsRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ListEventsRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *ListEventsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{2}
}

func (x *ListEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type Event struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title    string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	StartAt  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	Location string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	// Notification preferences for reminders.
	NotifyDayBefore  bool `protobuf:"varint,5,opt,name=notify_day_before,json=notifyDayBefore,proto3" json:"notify_day_before,omitempty"`
	NotifyHourBefore bool `protobuf:"varint,6,opt,name=notify_hour_before,json=notifyHourBefore,proto3" json:"notify_hour_before,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *Event) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Event) GetNotifyDayBefore() bool {
	if x != nil {
		return x.NotifyDayBefore
	}
	return false
}

func (x *Event) GetNotifyHourBefore() bool {
	if x != nil {
		return x.NotifyHourBefore
	}
	return false
}

type EventDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Tracklist     *Tracklist             `protobuf:"bytes,2,opt,name=tracklist,proto3" json:"tracklist,omitempty"`
	Participants  []*RoleAssignment      `protobuf:"bytes,3,rep,name=participants,proto3" json:"participants,omitempty"`
	Permissions   *PermissionSet         `protobuf:"bytes,4,opt,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventDetails) Reset() {
	*x = EventDetails{}
	mi := &file_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventDetails) ProtoMessage() {}

func (x *EventDetails) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventDetails.ProtoReflect.Descriptor instead.
func (*EventDetails) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{4}
}

func (x *EventDetails) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *EventDetails) GetTracklist() *Tracklist {
	if x != nil {
		return x.Tracklist
	}
	return nil
}

func (x *EventDetails) GetParticipants() []*RoleAssignment {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *EventDetails) GetPermissions() *PermissionSet {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type Tracklist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TrackItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tracklist) Reset() {
	*x = Tracklist{}
	mi := &file_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tracklist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tracklist) ProtoMessage() {}

func (x *Tracklist) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tracklist.ProtoReflect.Descriptor instead.
func (*Tracklist) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{5}
}

func (x *Tracklist) GetItems() []*TrackItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type TrackItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Order uint32                 `protobuf:"varint,1,opt,name=order,proto3" json:"order,omitempty"`
	// Reference to a song in the catalog.
	SongId string `protobuf:"bytes,2,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	// If song is not in catalog, allow a custom title/artist.
	CustomTitle   string `protobuf:"bytes,3,opt,name=custom_title,json=customTitle,proto3" json:"custom_title,omitempty"`
	CustomArtist  string `protobuf:"bytes,4,opt,name=custom_artist,json=customArtist,proto3" json:"custom_artist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackItem) Reset() {
	*x = TrackItem{}
	mi := &file_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackItem) ProtoMessage() {}

func (x *TrackItem) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackItem.ProtoReflect.Descriptor instead.
func (*TrackItem) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{6}
}

func (x *TrackItem) GetOrder() uint32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *TrackItem) GetSongId() string {
	if x != nil {
		return x.SongId
	}
	return ""
}

func (x *TrackItem) GetCustomTitle() string {
	if x != nil {
		return x.CustomTitle
	}
	return ""
}

func (x *TrackItem) GetCustomArtist() string {
	if x != nil {
		return x.CustomArtist
	}
	return ""
}

type CreateEventRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Title            string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	StartAt          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	Location         string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	NotifyDayBefore  bool                   `protobuf:"varint,4,opt,name=notify_day_before,json=notifyDayBefore,proto3" json:"notify_day_before,omitempty"`
	NotifyHourBefore bool                   `protobuf:"varint,5,opt,name=notify_hour_before,json=notifyHourBefore,proto3" json:"notify_hour_before,omitempty"`
	Tracklist        *Tracklist             `protobuf:"bytes,6,opt,name=tracklist,proto3" json:"tracklist,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{7}
}

func (x *CreateEventRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateEventRequest) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *CreateEventRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateEventRequest) GetNotifyDayBefore() bool {
	if x != nil {
		return x.NotifyDayBefore
	}
	return false
}

func (x *CreateEventRequest) GetNotifyHourBefore() bool {
	if x != nil {
		return x.NotifyHourBefore
	}
	return false
}

func (x *CreateEventRequest) GetTracklist() *Tracklist {
	if x != nil {
		return x.Tracklist
	}
	return nil
}

type UpdateEventRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	StartAt          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	Location         string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	NotifyDayBefore  bool                   `protobuf:"varint,5,opt,name=notify_day_before,json=notifyDayBefore,proto3" json:"notify_day_before,omitempty"`
	NotifyHourBefore bool                   `protobuf:"varint,6,opt,name=notify_hour_before,json=notifyHourBefore,proto3" json:"notify_hour_before,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateEventRequest) Reset() {
	*x = UpdateEventRequest{}
	mi := &file_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventRequest) ProtoMessage() {}

func (x *UpdateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateEventRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateEventRequest) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *UpdateEventRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateEventRequest) GetNotifyDayBefore() bool {
	if x != nil {
		return x.NotifyDayBefore
	}
	return false
}

func (x *UpdateEventRequest) GetNotifyHourBefore() bool {
	if x != nil {
		return x.NotifyHourBefore
	}
	return false
}

type SetTracklistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Tracklist     *Tracklist             `protobuf:"bytes,2,opt,name=tracklist,proto3" json:"tracklist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTracklistRequest) Reset() {
	*x = SetTracklistRequest{}
	mi := &file_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTracklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTracklistRequest) ProtoMessage() {}

func (x *SetTracklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTracklistRequest.ProtoReflect.Descriptor instead.
func (*SetTracklistRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{9}
}

func (x *SetTracklistRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *SetTracklistRequest) GetTracklist() *Tracklist {
	if x != nil {
		return x.Tracklist
	}
	return nil
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\x0fmusicclub.event\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\n" +
	"song.proto\x1a\n" +
	"user.proto\x1a\x11permissions.proto\"\x19\n" +
	"\aEventId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x85\x01\n" +
	"\x11ListEventsRequest\x12.\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"D\n" +
	"\x12ListEventsResponse\x12.\n" +
	"\x06events\x18\x01 \x03(\v2\x16.musicclub.event.EventR\x06events\"\xda\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x125\n" +
	"\bstart_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\astartAt\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12*\n" +
	"\x11notify_day_before\x18\x05 \x01(\bR\x0fnotifyDayBefore\x12,\n" +
	"\x12notify_hour_before\x18\x06 \x01(\bR\x10notifyHourBefore\"\x82\x02\n" +
	"\fEventDetails\x12,\n" +
	"\x05event\x18\x01 \x01(\v2\x16.musicclub.event.EventR\x05event\x128\n" +
	"\ttracklist\x18\x02 \x01(\v2\x1a.musicclub.event.TracklistR\ttracklist\x12B\n" +
	"\fparticipants\x18\x03 \x03(\v2\x1e.musicclub.song.RoleAssignmentR\fparticipants\x12F\n" +
	"\vpermissions\x18\x04 \x01(\v2$.musicclub.permissions.PermissionSetR\vpermissions\"=\n" +
	"\tTracklist\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.musicclub.event.TrackItemR\x05items\"\x82\x01\n" +
	"\tTrackItem\x12\x14\n" +
	"\x05order\x18\x01 \x01(\rR\x05order\x12\x17\n" +
	"\asong_id\x18\x02 \x01(\tR\x06songId\x12!\n" +
	"\fcustom_title\x18\x03 \x01(\tR\vcustomTitle\x12#\n" +
	"\rcustom_artist\x18\x04 \x01(\tR\fcustomArtist\"\x91\x02\n" +
	"\x12CreateEventRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x125\n" +
	"\bstart_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\astartAt\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12*\n" +
	"\x11notify_day_before\x18\x04 \x01(\bR\x0fnotifyDayBefore\x12,\n" +
	"\x12notify_hour_before\x18\x05 \x01(\bR\x10notifyHourBefore\x128\n" +
	"\ttracklist\x18\x06 \x01(\v2\x1a.musicclub.event.TracklistR\ttracklist\"\xe7\x01\n" +
	"\x12UpdateEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x125\n" +
	"\bstart_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\astartAt\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12*\n" +
	"\x11notify_day_before\x18\x05 \x01(\bR\x0fnotifyDayBefore\x12,\n" +
	"\x12notify_hour_before\x18\x06 \x01(\bR\x10notifyHourBefore\"j\n" +
	"\x13SetTracklistRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x128\n" +
	"\ttracklist\x18\x02 \x01(\v2\x1a.musicclub.event.TracklistR\ttracklist2\xe6\x03\n" +
	"\fEventService\x12U\n" +
	"\n" +
	"ListEvents\x12\".musicclub.event.ListEventsRequest\x1a#.musicclub.event.ListEventsResponse\x12C\n" +
	"\bGetEvent\x12\x18.musicclub.event.EventId\x1a\x1d.musicclub.event.EventDetails\x12Q\n" +
	"\vCreateEvent\x12#.musicclub.event.CreateEventRequest\x1a\x1d.musicclub.event.EventDetails\x12Q\n" +
	"\vUpdateEvent\x12#.musicclub.event.UpdateEventRequest\x1a\x1d.musicclub.event.EventDetails\x12?\n" +
	"\vDeleteEvent\x12\x18.musicclub.event.EventId\x1a\x16.google.protobuf.Empty\x12S\n" +
	"\fSetTracklist\x12$.musicclub.event.SetTracklistRequest\x1a\x1d.musicclub.event.EventDetailsB\x1cZ\x1amusicclubbot/backend/protob\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_event_proto_goTypes = []any{
	(*EventId)(nil),               // 0: musicclub.event.EventId
	(*ListEventsRequest)(nil),     // 1: musicclub.event.ListEventsRequest
	(*ListEventsResponse)(nil),    // 2: musicclub.event.ListEventsResponse
	(*Event)(nil),                 // 3: musicclub.event.Event
	(*EventDetails)(nil),          // 4: musicclub.event.EventDetails
	(*Tracklist)(nil),             // 5: musicclub.event.Tracklist
	(*TrackItem)(nil),             // 6: musicclub.event.TrackItem
	(*CreateEventRequest)(nil),    // 7: musicclub.event.CreateEventRequest
	(*UpdateEventRequest)(nil),    // 8: musicclub.event.UpdateEventRequest
	(*SetTracklistRequest)(nil),   // 9: musicclub.event.SetTracklistRequest
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*RoleAssignment)(nil),        // 11: musicclub.song.RoleAssignment
	(*PermissionSet)(nil),         // 12: musicclub.permissions.PermissionSet
	(*emptypb.Empty)(nil),         // 13: google.protobuf.Empty
}
var file_event_proto_depIdxs = []int32{
	10, // 0: musicclub.event.ListEventsRequest.from:type_name -> google.protobuf.Timestamp
	10, // 1: musicclub.event.ListEventsRequest.to:type_name -> google.protobuf.Timestamp
	3,  // 2: musicclub.event.ListEventsResponse.events:type_name -> musicclub.event.Event
	10, // 3: musicclub.event.Event.start_at:type_name -> google.protobuf.Timestamp
	3,  // 4: musicclub.event.EventDetails.event:type_name -> musicclub.event.Event
	5,  // 5: musicclub.event.EventDetails.tracklist:type_name -> musicclub.event.Tracklist
	11, // 6: musicclub.event.EventDetails.participants:type_name -> musicclub.song.RoleAssignment
	12, // 7: musicclub.event.EventDetails.permissions:type_name -> musicclub.permissions.PermissionSet
	6,  // 8: musicclub.event.Tracklist.items:type_name -> musicclub.event.TrackItem
	10, // 9: musicclub.event.CreateEventRequest.start_at:type_name -> google.protobuf.Timestamp
	5,  // 10: musicclub.event.CreateEventRequest.tracklist:type_name -> musicclub.event.Tracklist
	10, // 11: musicclub.event.UpdateEventRequest.start_at:type_name -> google.protobuf.Timestamp
	5,  // 12: musicclub.event.SetTracklistRequest.tracklist:type_name -> musicclub.event.Tracklist
	1,  // 13: musicclub.event.EventService.ListEvents:input_type -> musicclub.event.ListEventsRequest
	0,  // 14: musicclub.event.EventService.GetEvent:input_type -> musicclub.event.EventId
	7,  // 15: musicclub.event.EventService.CreateEvent:input_type -> musicclub.event.CreateEventRequest
	8,  // 16: musicclub.event.EventService.UpdateEvent:input_type -> musicclub.event.UpdateEventRequest
	0,  // 17: musicclub.event.EventService.DeleteEvent:input_type -> musicclub.event.EventId
	9,  // 18: musicclub.event.EventService.SetTracklist:input_type -> musicclub.event.SetTracklistRequest
	2,  // 19: musicclub.event.EventService.ListEvents:output_type -> musicclub.event.ListEventsResponse
	4,  // 20: musicclub.event.EventService.GetEvent:output_type -> musicclub.event.EventDetails
	4,  // 21: musicclub.event.EventService.CreateEvent:output_type -> musicclub.event.EventDetails
	4,  // 22: musicclub.event.EventService.UpdateEvent:output_type -> musicclub.event.EventDetails
	13, // 23: musicclub.event.EventService.DeleteEvent:output_type -> google.protobuf.Empty
	4,  // 24: musicclub.event.EventService.SetTracklist:output_type -> musicclub.event.EventDetails
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	file_song_proto_init()
	file_user_proto_init()
	file_permissions_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
