// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.3
// source: permissions.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Aggregated permissions for a user session.
type PermissionSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Join   *JoinPermissions  `protobuf:"bytes,1,opt,name=join,proto3" json:"join,omitempty"`
	Songs  *SongPermissions  `protobuf:"bytes,2,opt,name=songs,proto3" json:"songs,omitempty"`
	Events *EventPermissions `protobuf:"bytes,3,opt,name=events,proto3" json:"events,omitempty"`
}

func (x *PermissionSet) Reset() {
	*x = PermissionSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permissions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermissionSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionSet) ProtoMessage() {}

func (x *PermissionSet) ProtoReflect() protoreflect.Message {
	mi := &file_permissions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionSet.ProtoReflect.Descriptor instead.
func (*PermissionSet) Descriptor() ([]byte, []int) {
	return file_permissions_proto_rawDescGZIP(), []int{0}
}

func (x *PermissionSet) GetJoin() *JoinPermissions {
	if x != nil {
		return x.Join
	}
	return nil
}

func (x *PermissionSet) GetSongs() *SongPermissions {
	if x != nil {
		return x.Songs
	}
	return nil
}

func (x *PermissionSet) GetEvents() *EventPermissions {
	if x != nil {
		return x.Events
	}
	return nil
}

// Rights around participation in roles.
type JoinPermissions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EditOwnParticipation bool `protobuf:"varint,1,opt,name=edit_own_participation,json=editOwnParticipation,proto3" json:"edit_own_participation,omitempty"`
	EditAnyParticipation bool `protobuf:"varint,2,opt,name=edit_any_participation,json=editAnyParticipation,proto3" json:"edit_any_participation,omitempty"`
}

func (x *JoinPermissions) Reset() {
	*x = JoinPermissions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permissions_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinPermissions) ProtoMessage() {}

func (x *JoinPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_permissions_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinPermissions.ProtoReflect.Descriptor instead.
func (*JoinPermissions) Descriptor() ([]byte, []int) {
	return file_permissions_proto_rawDescGZIP(), []int{1}
}

func (x *JoinPermissions) GetEditOwnParticipation() bool {
	if x != nil {
		return x.EditOwnParticipation
	}
	return false
}

func (x *JoinPermissions) GetEditAnyParticipation() bool {
	if x != nil {
		return x.EditAnyParticipation
	}
	return false
}

// Rights around songs.
type SongPermissions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EditOwnSongs bool `protobuf:"varint,1,opt,name=edit_own_songs,json=editOwnSongs,proto3" json:"edit_own_songs,omitempty"`
	EditAnySongs bool `protobuf:"varint,2,opt,name=edit_any_songs,json=editAnySongs,proto3" json:"edit_any_songs,omitempty"`
}

func (x *SongPermissions) Reset() {
	*x = SongPermissions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permissions_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SongPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongPermissions) ProtoMessage() {}

func (x *SongPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_permissions_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongPermissions.ProtoReflect.Descriptor instead.
func (*SongPermissions) Descriptor() ([]byte, []int) {
	return file_permissions_proto_rawDescGZIP(), []int{2}
}

func (x *SongPermissions) GetEditOwnSongs() bool {
	if x != nil {
		return x.EditOwnSongs
	}
	return false
}

func (x *SongPermissions) GetEditAnySongs() bool {
	if x != nil {
		return x.EditAnySongs
	}
	return false
}

// Rights around events and tracklists.
type EventPermissions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EditEvents     bool `protobuf:"varint,1,opt,name=edit_events,json=editEvents,proto3" json:"edit_events,omitempty"`
	EditTracklists bool `protobuf:"varint,2,opt,name=edit_tracklists,json=editTracklists,proto3" json:"edit_tracklists,omitempty"`
}

func (x *EventPermissions) Reset() {
	*x = EventPermissions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permissions_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventPermissions) ProtoMessage() {}

func (x *EventPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_permissions_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventPermissions.ProtoReflect.Descriptor instead.
func (*EventPermissions) Descriptor() ([]byte, []int) {
	return file_permissions_proto_rawDescGZIP(), []int{3}
}

func (x *EventPermissions) GetEditEvents() bool {
	if x != nil {
		return x.EditEvents
	}
	return false
}

func (x *EventPermissions) GetEditTracklists() bool {
	if x != nil {
		return x.EditTracklists
	}
	return false
}

var File_permissions_proto protoreflect.FileDescriptor

var file_permissions_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x15, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x63, 0x6c, 0x75, 0x62, 0x2e, 0x70,
	0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xca, 0x01, 0x0a, 0x0d, 0x50,
	0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x12, 0x3a, 0x0a, 0x04,
	0x6a, 0x6f, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6d, 0x75, 0x73,
	0x69, 0x63, 0x63, 0x6c, 0x75, 0x62, 0x2e, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x04, 0x6a, 0x6f, 0x69, 0x6e, 0x12, 0x3c, 0x0a, 0x05, 0x73, 0x6f, 0x6e, 0x67,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x63,
	0x6c, 0x75, 0x62, 0x2e, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x53, 0x6f, 0x6e, 0x67, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x05, 0x73, 0x6f, 0x6e, 0x67, 0x73, 0x12, 0x3f, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x63, 0x6c,
	0x75, 0x62, 0x2e, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x7d, 0x0a, 0x0f, 0x4a, 0x6f, 0x69, 0x6e, 0x50,
	0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x34, 0x0a, 0x16, 0x65, 0x64,
	0x69, 0x74, 0x5f, 0x6f, 0x77, 0x6e, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x14, 0x65, 0x64, 0x69, 0x74,
	0x4f, 0x77, 0x6e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x34, 0x0a, 0x16, 0x65, 0x64, 0x69, 0x74, 0x5f, 0x61, 0x6e, 0x79, 0x5f, 0x70, 0x61, 0x72,
	0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x14, 0x65, 0x64, 0x69, 0x74, 0x41, 0x6e, 0x79, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69,
	0x70, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x5d, 0x0a, 0x0f, 0x53, 0x6f, 0x6e, 0x67, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x24, 0x0a, 0x0e, 0x65, 0x64, 0x69,
	0x74, 0x5f, 0x6f, 0x77, 0x6e, 0x5f, 0x73, 0x6f, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0c, 0x65, 0x64, 0x69, 0x74, 0x4f, 0x77, 0x6e, 0x53, 0x6f, 0x6e, 0x67, 0x73, 0x12,
	0x24, 0x0a, 0x0e, 0x65, 0x64, 0x69, 0x74, 0x5f, 0x61, 0x6e, 0x79, 0x5f, 0x73, 0x6f, 0x6e, 0x67,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x65, 0x64, 0x69, 0x74, 0x41, 0x6e, 0x79,
	0x53, 0x6f, 0x6e, 0x67, 0x73, 0x22, 0x5c, 0x0a, 0x10, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x64, 0x69,
	0x74, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a,
	0x65, 0x64, 0x69, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x64,
	0x69, 0x74, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0e, 0x65, 0x64, 0x69, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x6c, 0x69,
	0x73, 0x74, 0x73, 0x42, 0x1c, 0x5a, 0x1a, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x63, 0x6c, 0x75, 0x62,
	0x62, 0x6f, 0x74, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_permissions_proto_rawDescOnce sync.Once
	file_permissions_proto_rawDescData = file_permissions_proto_rawDesc
)

func file_permissions_proto_rawDescGZIP() []byte {
	file_permissions_proto_rawDescOnce.Do(func() {
		file_permissions_proto_rawDescData = protoimpl.X.CompressGZIP(file_permissions_proto_rawDescData)
	})
	return file_permissions_proto_rawDescData
}

var file_permissions_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_permissions_proto_goTypes = []any{
	(*PermissionSet)(nil),    // 0: musicclub.permissions.PermissionSet
	(*JoinPermissions)(nil),  // 1: musicclub.permissions.JoinPermissions
	(*SongPermissions)(nil),  // 2: musicclub.permissions.SongPermissions
	(*EventPermissions)(nil), // 3: musicclub.permissions.EventPermissions
}
var file_permissions_proto_depIdxs = []int32{
	1, // 0: musicclub.permissions.PermissionSet.join:type_name -> musicclub.permissions.JoinPermissions
	2, // 1: musicclub.permissions.PermissionSet.songs:type_name -> musicclub.permissions.SongPermissions
	3, // 2: musicclub.permissions.PermissionSet.events:type_name -> musicclub.permissions.EventPermissions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_permissions_proto_init() }
func file_permissions_proto_init() {
	if File_permissions_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_permissions_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PermissionSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_permissions_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*JoinPermissions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_permissions_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SongPermissions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_permissions_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*EventPermissions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_permissions_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_permissions_proto_goTypes,
		DependencyIndexes: file_permissions_proto_depIdxs,
		MessageInfos:      file_permissions_proto_msgTypes,
	}.Build()
	File_permissions_proto = out.File
	file_permissions_proto_rawDesc = nil
	file_permissions_proto_goTypes = nil
	file_permissions_proto_depIdxs = nil
}
