// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: permissions.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Aggregated permissions for a user session.
type PermissionSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Join          *JoinPermissions       `protobuf:"bytes,1,opt,name=join,proto3" json:"join,omitempty"`
	Songs         *SongPermissions       `protobuf:"bytes,2,opt,name=songs,proto3" json:"songs,omitempty"`
	Events        *EventPermissions      `protobuf:"bytes,3,opt,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionSet) Reset() {
	*x = PermissionSet{}
	mi := &file_permissions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionSet) ProtoMessage() {}

func (x *PermissionSet) ProtoReflect() protoreflect.Message {
	mi := &file_permissions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionSet.ProtoReflect.Descriptor instead.
func (*PermissionSet) Descriptor() ([]byte, []int) {
	return file_permissions_proto_rawDescGZIP(), []int{0}
}

func (x *PermissionSet) GetJoin() *JoinPermissions {
	if x != nil {
		return x.Join
	}
	return nil
}

func (x *PermissionSet) GetSongs() *SongPermissions {
	if x != nil {
		return x.Songs
	}
	return nil
}

func (x *PermissionSet) GetEvents() *EventPermissions {
	if x != nil {
		return x.Events
	}
	return nil
}

// Rights around participation in roles.
type JoinPermissions struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	EditOwnParticipation bool                   `protobuf:"varint,1,opt,name=edit_own_participation,json=editOwnParticipation,proto3" json:"edit_own_participation,omitempty"`
	EditAnyParticipation bool                   `protobuf:"varint,2,opt,name=edit_any_participation,json=editAnyParticipation,proto3" json:"edit_any_participation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *JoinPermissions) Reset() {
	*x = JoinPermissions{}
	mi := &file_permissions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinPermissions) ProtoMessage() {}

func (x *JoinPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_permissions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinPermissions.ProtoReflect.Descriptor instead.
func (*JoinPermissions) Descriptor() ([]byte, []int) {
	return file_permissions_proto_rawDescGZIP(), []int{1}
}

func (x *JoinPermissions) GetEditOwnParticipation() bool {
	if x != nil {
		return x.EditOwnParticipation
	}
	return false
}

func (x *JoinPermissions) GetEditAnyParticipation() bool {
	if x != nil {
		return x.EditAnyParticipation
	}
	return false
}

// Rights around songs.
type SongPermissions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EditOwnSongs  bool                   `protobuf:"varint,1,opt,name=edit_own_songs,json=editOwnSongs,proto3" json:"edit_own_songs,omitempty"`
	EditAnySongs  bool                   `protobuf:"varint,2,opt,name=edit_any_songs,json=editAnySongs,proto3" json:"edit_any_songs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SongPermissions) Reset() {
	*x = SongPermissions{}
	mi := &file_permissions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SongPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongPermissions) ProtoMessage() {}

func (x *SongPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_permissions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongPermissions.ProtoReflect.Descriptor instead.
func (*SongPermissions) Descriptor() ([]byte, []int) {
	return file_permissions_proto_rawDescGZIP(), []int{2}
}

func (x *SongPermissions) GetEditOwnSongs() bool {
	if x != nil {
		return x.EditOwnSongs
	}
	return false
}

func (x *SongPermissions) GetEditAnySongs() bool {
	if x != nil {
		return x.EditAnySongs
	}
	return false
}

// Rights around events and tracklists.
type EventPermissions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EditEvents     bool                   `protobuf:"varint,1,opt,name=edit_events,json=editEvents,proto3" json:"edit_events,omitempty"`
	EditTracklists bool                   `protobuf:"varint,2,opt,name=edit_tracklists,json=editTracklists,proto3" json:"edit_tracklists,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EventPermissions) Reset() {
	*x = EventPermissions{}
	mi := &file_permissions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventPermissions) ProtoMessage() {}

func (x *EventPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_permissions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventPermissions.ProtoReflect.Descriptor instead.
func (*EventPermissions) Descriptor() ([]byte, []int) {
	return file_permissions_proto_rawDescGZIP(), []int{3}
}

func (x *EventPermissions) GetEditEvents() bool {
	if x != nil {
		return x.EditEvents
	}
	return false
}

func (x *EventPermissions) GetEditTracklists() bool {
	if x != nil {
		return x.EditTracklists
	}
	return false
}

var File_permissions_proto protoreflect.FileDescriptor

const file_permissions_proto_rawDesc = "" +
	"\n" +
	"\x11permissions.proto\x12\x15musicclub.permissions\"\xca\x01\n" +
	"\rPermissionSet\x12:\n" +
	"\x04join\x18\x01 \x01(\v2&.musicclub.permissions.JoinPermissionsR\x04join\x12<\n" +
	"\x05songs\x18\x02 \x01(\v2&.musicclub.permissions.SongPermissionsR\x05songs\x12?\n" +
	"\x06events\x18\x03 \x01(\v2'.musicclub.permissions.EventPermissionsR\x06events\"}\n" +
	"\x0fJoinPermissions\x124\n" +
	"\x16edit_own_participation\x18\x01 \x01(\bR\x14editOwnParticipation\x124\n" +
	"\x16edit_any_participation\x18\x02 \x01(\bR\x14editAnyParticipation\"]\n" +
	"\x0fSongPermissions\x12$\n" +
	"\x0eedit_own_songs\x18\x01 \x01(\bR\feditOwnSongs\x12$\n" +
	"\x0eedit_any_songs\x18\x02 \x01(\bR\feditAnySongs\"\\\n" +
	"\x10EventPermissions\x12\x1f\n" +
	"\vedit_events\x18\x01 \x01(\bR\n" +
	"editEvents\x12'\n" +
	"\x0fedit_tracklists\x18\x02 \x01(\bR\x0eeditTracklistsB\x1cZ\x1amusicclubbot/backend/protob\x06proto3"

var (
	file_permissions_proto_rawDescOnce sync.Once
	file_permissions_proto_rawDescData []byte
)

func file_permissions_proto_rawDescGZIP() []byte {
	file_permissions_proto_rawDescOnce.Do(func() {
		file_permissions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_permissions_proto_rawDesc), len(file_permissions_proto_rawDesc)))
	})
	return file_permissions_proto_rawDescData
}

var file_permissions_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_permissions_proto_goTypes = []any{
	(*PermissionSet)(nil),    // 0: musicclub.permissions.PermissionSet
	(*JoinPermissions)(nil),  // 1: musicclub.permissions.JoinPermissions
	(*SongPermissions)(nil),  // 2: musicclub.permissions.SongPermissions
	(*EventPermissions)(nil), // 3: musicclub.permissions.EventPermissions
}
var file_permissions_proto_depIdxs = []int32{
	1, // 0: musicclub.permissions.PermissionSet.join:type_name -> musicclub.permissions.JoinPermissions
	2, // 1: musicclub.permissions.PermissionSet.songs:type_name -> musicclub.permissions.SongPermissions
	3, // 2: musicclub.permissions.PermissionSet.events:type_name -> musicclub.permissions.EventPermissions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_permissions_proto_init() }
func file_permissions_proto_init() {
	if File_permissions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_permissions_proto_rawDesc), len(file_permissions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_permissions_proto_goTypes,
		DependencyIndexes: file_permissions_proto_depIdxs,
		MessageInfos:      file_permissions_proto_msgTypes,
	}.Build()
	File_permissions_proto = out.File
	file_permissions_proto_goTypes = nil
	file_permissions_proto_depIdxs = nil
}
