// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: song.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SongLinkType int32

const (
	SongLinkType_SONG_LINK_TYPE_UNKNOWN      SongLinkType = 0
	SongLinkType_SONG_LINK_TYPE_YOUTUBE      SongLinkType = 1
	SongLinkType_SONG_LINK_TYPE_YANDEX_MUSIC SongLinkType = 2
	SongLinkType_SONG_LINK_TYPE_SOUNDCLOUD   SongLinkType = 3
)

// Enum value maps for SongLinkType.
var (
	SongLinkType_name = map[int32]string{
		0: "SONG_LINK_TYPE_UNKNOWN",
		1: "SONG_LINK_TYPE_YOUTUBE",
		2: "SONG_LINK_TYPE_YANDEX_MUSIC",
		3: "SONG_LINK_TYPE_SOUNDCLOUD",
	}
	SongLinkType_value = map[string]int32{
		"SONG_LINK_TYPE_UNKNOWN":      0,
		"SONG_LINK_TYPE_YOUTUBE":      1,
		"SONG_LINK_TYPE_YANDEX_MUSIC": 2,
		"SONG_LINK_TYPE_SOUNDCLOUD":   3,
	}
)

func (x SongLinkType) Enum() *SongLinkType {
	p := new(SongLinkType)
	*p = x
	return p
}

func (x SongLinkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SongLinkType) Descriptor() protoreflect.EnumDescriptor {
	return file_song_proto_enumTypes[0].Descriptor()
}

func (SongLinkType) Type() protoreflect.EnumType {
	return &file_song_proto_enumTypes[0]
}

func (x SongLinkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SongLinkType.Descriptor instead.
func (SongLinkType) EnumDescriptor() ([]byte, []int) {
	return file_song_proto_rawDescGZIP(), []int{0}
}

type ListSongsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional substring filter by title or artist.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Pagination cursor (opaque to client).
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	PageSize      uint32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSongsRequest) Reset() {
	*x = ListSongsRequest{}
	mi := &file_song_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSongsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSongsRequest) ProtoMessage() {}

func (x *ListSongsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_song_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSongsRequest.ProtoReflect.Descriptor instead.
func (*ListSongsRequest) Descriptor() ([]byte, []int) {
	return file_song_proto_rawDescGZIP(), []int{0}
}

func (x *ListSongsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListSongsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListSongsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListSongsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Songs         []*Song                `protobuf:"bytes,1,rep,name=songs,proto3" json:"songs,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSongsResponse) Reset() {
	*x = ListSongsResponse{}
	mi := &file_song_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSongsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSongsResponse) ProtoMessage() {}

func (x *ListSongsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_song_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSongsResponse.ProtoReflect.Descriptor instead.
func (*ListSongsResponse) Descriptor() ([]byte, []int) {
	return file_song_proto_rawDescGZIP(), []int{1}
}

func (x *ListSongsResponse) GetSongs() []*Song {
	if x != nil {
		return x.Songs
	}
	return nil
}

func (x *ListSongsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type SongId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SongId) Reset() {
	*x = SongId{}
	mi := &file_song_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SongId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongId) ProtoMessage() {}

func (x *SongId) ProtoReflect() protoreflect.Message {
	mi := &file_song_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongId.ProtoReflect.Descriptor instead.
func (*SongId) Descriptor() ([]byte, []int) {
	return file_song_proto_rawDescGZIP(), []int{2}
}

func (x *SongId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Song struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Artist         string                 `protobuf:"bytes,3,opt,name=artist,proto3" json:"artist,omitempty"`
	Link           *SongLink              `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	AvailableRoles []string               `protobuf:"bytes,6,rep,name=available_roles,json=availableRoles,proto3" json:"available_roles,omitempty"`
	// Whether current user may edit this song.
	EditableByMe bool `protobuf:"varint,7,opt,name=editable_by_me,json=editableByMe,proto3" json:"editable_by_me,omitempty"`
	// Number of participants currently assigned to this song.
	AssignmentCount int32 `protobuf:"varint,8,opt,name=assignment_count,json=assignmentCount,proto3" json:"assignment_count,omitempty"`
	// Thumbnail image URL (auto-extracted from link or custom).
	ThumbnailUrl  string `protobuf:"bytes,9,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Song) Reset() {
	*x = Song{}
	mi := &file_song_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Song) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Song) ProtoMessage() {}

func (x *Song) ProtoReflect() protoreflect.Message {
	mi := &file_song_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Song.ProtoReflect.Descriptor instead.
func (*Song) Descriptor() ([]byte, []int) {
	return file_song_proto_rawDescGZIP(), []int{3}
}

func (x *Song) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Song) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Song) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *Song) GetLink() *SongLink {
	if x != nil {
		return x.Link
	}
	return nil
}

func (x *Song) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Song) GetAvailableRoles() []string {
	if x != nil {
		return x.AvailableRoles
	}
	return nil
}

func (x *Song) GetEditableByMe() bool {
	if x != nil {
		return x.EditableByMe
	}
	return false
}

func (x *Song) GetAssignmentCount() int32 {
	if x != nil {
		return x.AssignmentCount
	}
	return 0
}

func (x *Song) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

type SongDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Song          *Song                  `protobuf:"bytes,1,opt,name=song,proto3" json:"song,omitempty"`
	Assignments   []*RoleAssignment      `protobuf:"bytes,2,rep,name=assignments,proto3" json:"assignments,omitempty"`
	Permissions   *PermissionSet         `protobuf:"bytes,3,opt,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SongDetails) Reset() {
	*x = SongDetails{}
	mi := &file_song_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SongDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongDetails) ProtoMessage() {}

func (x *SongDetails) ProtoReflect() protoreflect.Message {
	mi := &file_song_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongDetails.ProtoReflect.Descriptor instead.
func (*SongDetails) Descriptor() ([]byte, []int) {
	return file_song_proto_rawDescGZIP(), []int{4}
}

func (x *SongDetails) GetSong() *Song {
	if x != nil {
		return x.Song
	}
	return nil
}

func (x *SongDetails) GetAssignments() []*RoleAssignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

func (x *SongDetails) GetPermissions() *PermissionSet {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type SongLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          SongLinkType           `protobuf:"varint,1,opt,name=kind,proto3,enum=musicclub.song.SongLinkType" json:"kind,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SongLink) Reset() {
	*x = SongLink{}
	mi := &file_song_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SongLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongLink) ProtoMessage() {}

func (x *SongLink) ProtoReflect() protoreflect.Message {
	mi := &file_song_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongLink.ProtoReflect.Descriptor instead.
func (*SongLink) Descriptor() ([]byte, []int) {
	return file_song_proto_rawDescGZIP(), []int{5}
}

func (x *SongLink) GetKind() SongLinkType {
	if x != nil {
		return x.Kind
	}
	return SongLinkType_SONG_LINK_TYPE_UNKNOWN
}

func (x *SongLink) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type RoleAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleAssignment) Reset() {
	*x = RoleAssignment{}
	mi := &file_song_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAssignment) ProtoMessage() {}

func (x *RoleAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_song_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAssignment.ProtoReflect.Descriptor instead.
func (*RoleAssignment) Descriptor() ([]byte, []int) {
	return file_song_proto_rawDescGZIP(), []int{6}
}

func (x *RoleAssignment) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RoleAssignment) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *RoleAssignment) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

type CreateSongRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Title          string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Artist         string                 `protobuf:"bytes,2,opt,name=artist,proto3" json:"artist,omitempty"`
	Link           *SongLink              `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	AvailableRoles []string               `protobuf:"bytes,5,rep,name=available_roles,json=availableRoles,proto3" json:"available_roles,omitempty"`
	ThumbnailUrl   string                 `protobuf:"bytes,6,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateSongRequest) Reset() {
	*x = CreateSongRequest{}
	mi := &file_song_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSongRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSongRequest) ProtoMessage() {}

func (x *CreateSongRequest) ProtoReflect() protoreflect.Message {
	mi := &file_song_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSongRequest.ProtoReflect.Descriptor instead.
func (*CreateSongRequest) Descriptor() ([]byte, []int) {
	return file_song_proto_rawDescGZIP(), []int{7}
}

func (x *CreateSongRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSongRequest) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *CreateSongRequest) GetLink() *SongLink {
	if x != nil {
		return x.Link
	}
	return nil
}

func (x *CreateSongRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateSongRequest) GetAvailableRoles() []string {
	if x != nil {
		return x.AvailableRoles
	}
	return nil
}

func (x *CreateSongRequest) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

type UpdateSongRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Artist         string                 `protobuf:"bytes,3,opt,name=artist,proto3" json:"artist,omitempty"`
	Link           *SongLink              `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	AvailableRoles []string               `protobuf:"bytes,6,rep,name=available_roles,json=availableRoles,proto3" json:"available_roles,omitempty"`
	ThumbnailUrl   string                 `protobuf:"bytes,7,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateSongRequest) Reset() {
	*x = UpdateSongRequest{}
	mi := &file_song_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSongRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSongRequest) ProtoMessage() {}

func (x *UpdateSongRequest) ProtoReflect() protoreflect.Message {
	mi := &file_song_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSongRequest.ProtoReflect.Descriptor instead.
func (*UpdateSongRequest) Descriptor() ([]byte, []int) {
	return file_song_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateSongRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSongRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateSongRequest) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *UpdateSongRequest) GetLink() *SongLink {
	if x != nil {
		return x.Link
	}
	return nil
}

func (x *UpdateSongRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateSongRequest) GetAvailableRoles() []string {
	if x != nil {
		return x.AvailableRoles
	}
	return nil
}

func (x *UpdateSongRequest) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

type JoinRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SongId        string                 `protobuf:"bytes,1,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoleRequest) Reset() {
	*x = JoinRoleRequest{}
	mi := &file_song_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoleRequest) ProtoMessage() {}

func (x *JoinRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_song_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoleRequest.ProtoReflect.Descriptor instead.
func (*JoinRoleRequest) Descriptor() ([]byte, []int) {
	return file_song_proto_rawDescGZIP(), []int{9}
}

func (x *JoinRoleRequest) GetSongId() string {
	if x != nil {
		return x.SongId
	}
	return ""
}

func (x *JoinRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type LeaveRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SongId        string                 `protobuf:"bytes,1,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoleRequest) Reset() {
	*x = LeaveRoleRequest{}
	mi := &file_song_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoleRequest) ProtoMessage() {}

func (x *LeaveRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_song_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoleRequest.ProtoReflect.Descriptor instead.
func (*LeaveRoleRequest) Descriptor() ([]byte, []int) {
	return file_song_proto_rawDescGZIP(), []int{10}
}

func (x *LeaveRoleRequest) GetSongId() string {
	if x != nil {
		return x.SongId
	}
	return ""
}

func (x *LeaveRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_song_proto protoreflect.FileDescriptor

const file_song_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"song.proto\x12\x0emusicclub.song\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\n" +
	"user.proto\x1a\x11permissions.proto\"d\n" +
	"\x10ListSongsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\"g\n" +
	"\x11ListSongsResponse\x12*\n" +
	"\x05songs\x18\x01 \x03(\v2\x14.musicclub.song.SongR\x05songs\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x18\n" +
	"\x06SongId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb3\x02\n" +
	"\x04Song\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\x03 \x01(\tR\x06artist\x12,\n" +
	"\x04link\x18\x04 \x01(\v2\x18.musicclub.song.SongLinkR\x04link\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12'\n" +
	"\x0favailable_roles\x18\x06 \x03(\tR\x0eavailableRoles\x12$\n" +
	"\x0eeditable_by_me\x18\a \x01(\bR\feditableByMe\x12)\n" +
	"\x10assignment_count\x18\b \x01(\x05R\x0fassignmentCount\x12#\n" +
	"\rthumbnail_url\x18\t \x01(\tR\fthumbnailUrl\"\xc1\x01\n" +
	"\vSongDetails\x12(\n" +
	"\x04song\x18\x01 \x01(\v2\x14.musicclub.song.SongR\x04song\x12@\n" +
	"\vassignments\x18\x02 \x03(\v2\x1e.musicclub.song.RoleAssignmentR\vassignments\x12F\n" +
	"\vpermissions\x18\x03 \x01(\v2$.musicclub.permissions.PermissionSetR\vpermissions\"N\n" +
	"\bSongLink\x120\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1c.musicclub.song.SongLinkTypeR\x04kind\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"\x87\x01\n" +
	"\x0eRoleAssignment\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12(\n" +
	"\x04user\x18\x02 \x01(\v2\x14.musicclub.user.UserR\x04user\x127\n" +
	"\tjoined_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\"\xdf\x01\n" +
	"\x11CreateSongRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\x02 \x01(\tR\x06artist\x12,\n" +
	"\x04link\x18\x03 \x01(\v2\x18.musicclub.song.SongLinkR\x04link\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12'\n" +
	"\x0favailable_roles\x18\x05 \x03(\tR\x0eavailableRoles\x12#\n" +
	"\rthumbnail_url\x18\x06 \x01(\tR\fthumbnailUrl\"\xef\x01\n" +
	"\x11UpdateSongRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\x03 \x01(\tR\x06artist\x12,\n" +
	"\x04link\x18\x04 \x01(\v2\x18.musicclub.song.SongLinkR\x04link\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12'\n" +
	"\x0favailable_roles\x18\x06 \x03(\tR\x0eavailableRoles\x12#\n" +
	"\rthumbnail_url\x18\a \x01(\tR\fthumbnailUrl\">\n" +
	"\x0fJoinRoleRequest\x12\x17\n" +
	"\asong_id\x18\x01 \x01(\tR\x06songId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"?\n" +
	"\x10LeaveRoleRequest\x12\x17\n" +
	"\asong_id\x18\x01 \x01(\tR\x06songId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role*\x86\x01\n" +
	"\fSongLinkType\x12\x1a\n" +
	"\x16SONG_LINK_TYPE_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16SONG_LINK_TYPE_YOUTUBE\x10\x01\x12\x1f\n" +
	"\x1bSONG_LINK_TYPE_YANDEX_MUSIC\x10\x02\x12\x1d\n" +
	"\x19SONG_LINK_TYPE_SOUNDCLOUD\x10\x032\x8f\x04\n" +
	"\vSongService\x12P\n" +
	"\tListSongs\x12 .musicclub.song.ListSongsRequest\x1a!.musicclub.song.ListSongsResponse\x12>\n" +
	"\aGetSong\x12\x16.musicclub.song.SongId\x1a\x1b.musicclub.song.SongDetails\x12L\n" +
	"\n" +
	"CreateSong\x12!.musicclub.song.CreateSongRequest\x1a\x1b.musicclub.song.SongDetails\x12L\n" +
	"\n" +
	"UpdateSong\x12!.musicclub.song.UpdateSongRequest\x1a\x1b.musicclub.song.SongDetails\x12<\n" +
	"\n" +
	"DeleteSong\x12\x16.musicclub.song.SongId\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\bJoinRole\x12\x1f.musicclub.song.JoinRoleRequest\x1a\x1b.musicclub.song.SongDetails\x12J\n" +
	"\tLeaveRole\x12 .musicclub.song.LeaveRoleRequest\x1a\x1b.musicclub.song.SongDetailsB\x1cZ\x1amusicclubbot/backend/protob\x06proto3"

var (
	file_song_proto_rawDescOnce sync.Once
	file_song_proto_rawDescData []byte
)

func file_song_proto_rawDescGZIP() []byte {
	file_song_proto_rawDescOnce.Do(func() {
		file_song_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_song_proto_rawDesc), len(file_song_proto_rawDesc)))
	})
	return file_song_proto_rawDescData
}

var file_song_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_song_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_song_proto_goTypes = []any{
	(SongLinkType)(0),             // 0: musicclub.song.SongLinkType
	(*ListSongsRequest)(nil),      // 1: musicclub.song.ListSongsRequest
	(*ListSongsResponse)(nil),     // 2: musicclub.song.ListSongsResponse
	(*SongId)(nil),                // 3: musicclub.song.SongId
	(*Song)(nil),                  // 4: musicclub.song.Song
	(*SongDetails)(nil),           // 5: musicclub.song.SongDetails
	(*SongLink)(nil),              // 6: musicclub.song.SongLink
	(*RoleAssignment)(nil),        // 7: musicclub.song.RoleAssignment
	(*CreateSongRequest)(nil),     // 8: musicclub.song.CreateSongRequest
	(*UpdateSongRequest)(nil),     // 9: musicclub.song.UpdateSongRequest
	(*JoinRoleRequest)(nil),       // 10: musicclub.song.JoinRoleRequest
	(*LeaveRoleRequest)(nil),      // 11: musicclub.song.LeaveRoleRequest
	(*PermissionSet)(nil),         // 12: musicclub.permissions.PermissionSet
	(*User)(nil),                  // 13: musicclub.user.User
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 15: google.protobuf.Empty
}
var file_song_proto_depIdxs = []int32{
	4,  // 0: musicclub.song.ListSongsResponse.songs:type_name -> musicclub.song.Song
	6,  // 1: musicclub.song.Song.link:type_name -> musicclub.song.SongLink
	4,  // 2: musicclub.song.SongDetails.song:type_name -> musicclub.song.Song
	7,  // 3: musicclub.song.SongDetails.assignments:type_name -> musicclub.song.RoleAssignment
	12, // 4: musicclub.song.SongDetails.permissions:type_name -> musicclub.permissions.PermissionSet
	0,  // 5: musicclub.song.SongLink.kind:type_name -> musicclub.song.SongLinkType
	13, // 6: musicclub.song.RoleAssignment.user:type_name -> musicclub.user.User
	14, // 7: musicclub.song.RoleAssignment.joined_at:type_name -> google.protobuf.Timestamp
	6,  // 8: musicclub.song.CreateSongRequest.link:type_name -> musicclub.song.SongLink
	6,  // 9: musicclub.song.UpdateSongRequest.link:type_name -> musicclub.song.SongLink
	1,  // 10: musicclub.song.SongService.ListSongs:input_type -> musicclub.song.ListSongsRequest
	3,  // 11: musicclub.song.SongService.GetSong:input_type -> musicclub.song.SongId
	8,  // 12: musicclub.song.SongService.CreateSong:input_type -> musicclub.song.CreateSongRequest
	9,  // 13: musicclub.song.SongService.UpdateSong:input_type -> musicclub.song.UpdateSongRequest
	3,  // 14: musicclub.song.SongService.DeleteSong:input_type -> musicclub.song.SongId
	10, // 15: musicclub.song.SongService.JoinRole:input_type -> musicclub.song.JoinRoleRequest
	11, // 16: musicclub.song.SongService.LeaveRole:input_type -> musicclub.song.LeaveRoleRequest
	2,  // 17: musicclub.song.SongService.ListSongs:output_type -> musicclub.song.ListSongsResponse
	5,  // 18: musicclub.song.SongService.GetSong:output_type -> musicclub.song.SongDetails
	5,  // 19: musicclub.song.SongService.CreateSong:output_type -> musicclub.song.SongDetails
	5,  // 20: musicclub.song.SongService.UpdateSong:output_type -> musicclub.song.SongDetails
	15, // 21: musicclub.song.SongService.DeleteSong:output_type -> google.protobuf.Empty
	5,  // 22: musicclub.song.SongService.JoinRole:output_type -> musicclub.song.SongDetails
	5,  // 23: musicclub.song.SongService.LeaveRole:output_type -> musicclub.song.SongDetails
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_song_proto_init() }
func file_song_proto_init() {
	if File_song_proto != nil {
		return
	}
	file_user_proto_init()
	file_permissions_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_song_proto_rawDesc), len(file_song_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_song_proto_goTypes,
		DependencyIndexes: file_song_proto_depIdxs,
		EnumInfos:         file_song_proto_enumTypes,
		MessageInfos:      file_song_proto_msgTypes,
	}.Build()
	File_song_proto = out.File
	file_song_proto_goTypes = nil
	file_song_proto_depIdxs = nil
}
