// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.28.3
// source: song.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SongService_ListSongs_FullMethodName  = "/musicclub.song.SongService/ListSongs"
	SongService_GetSong_FullMethodName    = "/musicclub.song.SongService/GetSong"
	SongService_CreateSong_FullMethodName = "/musicclub.song.SongService/CreateSong"
	SongService_UpdateSong_FullMethodName = "/musicclub.song.SongService/UpdateSong"
	SongService_DeleteSong_FullMethodName = "/musicclub.song.SongService/DeleteSong"
	SongService_JoinRole_FullMethodName   = "/musicclub.song.SongService/JoinRole"
	SongService_LeaveRole_FullMethodName  = "/musicclub.song.SongService/LeaveRole"
)

// SongServiceClient is the client API for SongService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SongServiceClient interface {
	// Returns a paginated list of songs.
	ListSongs(ctx context.Context, in *ListSongsRequest, opts ...grpc.CallOption) (*ListSongsResponse, error)
	// Returns a single song with full metadata and assignments.
	GetSong(ctx context.Context, in *SongId, opts ...grpc.CallOption) (*SongDetails, error)
	// Create songs (requires permissions).
	CreateSong(ctx context.Context, in *CreateSongRequest, opts ...grpc.CallOption) (*SongDetails, error)
	// Update songs (requires permissions).
	UpdateSong(ctx context.Context, in *UpdateSongRequest, opts ...grpc.CallOption) (*SongDetails, error)
	// Delete songs (requires permissions).
	DeleteSong(ctx context.Context, in *SongId, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Join a role for a song.
	JoinRole(ctx context.Context, in *JoinRoleRequest, opts ...grpc.CallOption) (*SongDetails, error)
	// Leave a role for a song.
	LeaveRole(ctx context.Context, in *LeaveRoleRequest, opts ...grpc.CallOption) (*SongDetails, error)
}

type songServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSongServiceClient(cc grpc.ClientConnInterface) SongServiceClient {
	return &songServiceClient{cc}
}

func (c *songServiceClient) ListSongs(ctx context.Context, in *ListSongsRequest, opts ...grpc.CallOption) (*ListSongsResponse, error) {
	out := new(ListSongsResponse)
	err := c.cc.Invoke(ctx, SongService_ListSongs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *songServiceClient) GetSong(ctx context.Context, in *SongId, opts ...grpc.CallOption) (*SongDetails, error) {
	out := new(SongDetails)
	err := c.cc.Invoke(ctx, SongService_GetSong_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *songServiceClient) CreateSong(ctx context.Context, in *CreateSongRequest, opts ...grpc.CallOption) (*SongDetails, error) {
	out := new(SongDetails)
	err := c.cc.Invoke(ctx, SongService_CreateSong_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *songServiceClient) UpdateSong(ctx context.Context, in *UpdateSongRequest, opts ...grpc.CallOption) (*SongDetails, error) {
	out := new(SongDetails)
	err := c.cc.Invoke(ctx, SongService_UpdateSong_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *songServiceClient) DeleteSong(ctx context.Context, in *SongId, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SongService_DeleteSong_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *songServiceClient) JoinRole(ctx context.Context, in *JoinRoleRequest, opts ...grpc.CallOption) (*SongDetails, error) {
	out := new(SongDetails)
	err := c.cc.Invoke(ctx, SongService_JoinRole_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *songServiceClient) LeaveRole(ctx context.Context, in *LeaveRoleRequest, opts ...grpc.CallOption) (*SongDetails, error) {
	out := new(SongDetails)
	err := c.cc.Invoke(ctx, SongService_LeaveRole_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SongServiceServer is the server API for SongService service.
// All implementations must embed UnimplementedSongServiceServer
// for forward compatibility
type SongServiceServer interface {
	// Returns a paginated list of songs.
	ListSongs(context.Context, *ListSongsRequest) (*ListSongsResponse, error)
	// Returns a single song with full metadata and assignments.
	GetSong(context.Context, *SongId) (*SongDetails, error)
	// Create songs (requires permissions).
	CreateSong(context.Context, *CreateSongRequest) (*SongDetails, error)
	// Update songs (requires permissions).
	UpdateSong(context.Context, *UpdateSongRequest) (*SongDetails, error)
	// Delete songs (requires permissions).
	DeleteSong(context.Context, *SongId) (*emptypb.Empty, error)
	// Join a role for a song.
	JoinRole(context.Context, *JoinRoleRequest) (*SongDetails, error)
	// Leave a role for a song.
	LeaveRole(context.Context, *LeaveRoleRequest) (*SongDetails, error)
	mustEmbedUnimplementedSongServiceServer()
}

// UnimplementedSongServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSongServiceServer struct {
}

func (UnimplementedSongServiceServer) ListSongs(context.Context, *ListSongsRequest) (*ListSongsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSongs not implemented")
}
func (UnimplementedSongServiceServer) GetSong(context.Context, *SongId) (*SongDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSong not implemented")
}
func (UnimplementedSongServiceServer) CreateSong(context.Context, *CreateSongRequest) (*SongDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSong not implemented")
}
func (UnimplementedSongServiceServer) UpdateSong(context.Context, *UpdateSongRequest) (*SongDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSong not implemented")
}
func (UnimplementedSongServiceServer) DeleteSong(context.Context, *SongId) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSong not implemented")
}
func (UnimplementedSongServiceServer) JoinRole(context.Context, *JoinRoleRequest) (*SongDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinRole not implemented")
}
func (UnimplementedSongServiceServer) LeaveRole(context.Context, *LeaveRoleRequest) (*SongDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveRole not implemented")
}
func (UnimplementedSongServiceServer) mustEmbedUnimplementedSongServiceServer() {}

// UnsafeSongServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SongServiceServer will
// result in compilation errors.
type UnsafeSongServiceServer interface {
	mustEmbedUnimplementedSongServiceServer()
}

func RegisterSongServiceServer(s grpc.ServiceRegistrar, srv SongServiceServer) {
	s.RegisterService(&SongService_ServiceDesc, srv)
}

func _SongService_ListSongs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSongsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SongServiceServer).ListSongs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SongService_ListSongs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SongServiceServer).ListSongs(ctx, req.(*ListSongsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SongService_GetSong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SongId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SongServiceServer).GetSong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SongService_GetSong_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SongServiceServer).GetSong(ctx, req.(*SongId))
	}
	return interceptor(ctx, in, info, handler)
}

func _SongService_CreateSong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSongRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SongServiceServer).CreateSong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SongService_CreateSong_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SongServiceServer).CreateSong(ctx, req.(*CreateSongRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SongService_UpdateSong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSongRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SongServiceServer).UpdateSong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SongService_UpdateSong_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SongServiceServer).UpdateSong(ctx, req.(*UpdateSongRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SongService_DeleteSong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SongId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SongServiceServer).DeleteSong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SongService_DeleteSong_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SongServiceServer).DeleteSong(ctx, req.(*SongId))
	}
	return interceptor(ctx, in, info, handler)
}

func _SongService_JoinRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SongServiceServer).JoinRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SongService_JoinRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SongServiceServer).JoinRole(ctx, req.(*JoinRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SongService_LeaveRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SongServiceServer).LeaveRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SongService_LeaveRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SongServiceServer).LeaveRole(ctx, req.(*LeaveRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SongService_ServiceDesc is the grpc.ServiceDesc for SongService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SongService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "musicclub.song.SongService",
	HandlerType: (*SongServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSongs",
			Handler:    _SongService_ListSongs_Handler,
		},
		{
			MethodName: "GetSong",
			Handler:    _SongService_GetSong_Handler,
		},
		{
			MethodName: "CreateSong",
			Handler:    _SongService_CreateSong_Handler,
		},
		{
			MethodName: "UpdateSong",
			Handler:    _SongService_UpdateSong_Handler,
		},
		{
			MethodName: "DeleteSong",
			Handler:    _SongService_DeleteSong_Handler,
		},
		{
			MethodName: "JoinRole",
			Handler:    _SongService_JoinRole_Handler,
		},
		{
			MethodName: "LeaveRole",
			Handler:    _SongService_LeaveRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "song.proto",
}
