// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=ts"
// @generated from file auth.proto (package musicclub.auth, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import type { PermissionSet } from "./permissions_pb.ts";
import { file_permissions } from "./permissions_pb.ts";
import type { User, UserSchema } from "./user_pb.ts";
import { file_user } from "./user_pb.ts";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file auth.proto.
 */
export const file_auth: GenFile = /*@__PURE__*/
  fileDesc("CgphdXRoLnByb3RvEg5tdXNpY2NsdWIuYXV0aCIxCgtDcmVkZW50aWFscxIQCgh1c2VybmFtZRgBIAEoCRIQCghwYXNzd29yZBgCIAEoCSJuChNSZWdpc3RlclVzZXJSZXF1ZXN0EjAKC2NyZWRlbnRpYWxzGAEgASgLMhsubXVzaWNjbHViLmF1dGguQ3JlZGVudGlhbHMSJQoHcHJvZmlsZRgCIAEoCzIULm11c2ljY2x1Yi51c2VyLlVzZXIiJwoOUmVmcmVzaFJlcXVlc3QSFQoNcmVmcmVzaF90b2tlbhgBIAEoCSI4CglUb2tlblBhaXISFAoMYWNjZXNzX3Rva2VuGAEgASgJEhUKDXJlZnJlc2hfdG9rZW4YAiABKAkiKQoTVGdMb2dpbkxpbmtSZXNwb25zZRISCgpsb2dpbl9saW5rGAEgASgJIkgKDlRnTG9naW5SZXF1ZXN0EiIKBHVzZXIYASABKAsyFC5tdXNpY2NsdWIudXNlci5Vc2VyEhIKCnRnX3VzZXJfaWQYAiABKAQi5gEKC0F1dGhTZXNzaW9uEikKBnRva2VucxgBIAEoCzIZLm11c2ljY2x1Yi5hdXRoLlRva2VuUGFpchILCgNpYXQYAiABKAQSCwoDZXhwGAMgASgEEhYKDmlzX2NoYXRfbWVtYmVyGAQgASgIEhgKEGpvaW5fcmVxdWVzdF91cmwYBSABKAkSJQoHcHJvZmlsZRgGIAEoCzIULm11c2ljY2x1Yi51c2VyLlVzZXISOQoLcGVybWlzc2lvbnMYByABKAsyJC5tdXNpY2NsdWIucGVybWlzc2lvbnMuUGVybWlzc2lvblNldCJzCg9Qcm9maWxlUmVzcG9uc2USJQoHcHJvZmlsZRgBIAEoCzIULm11c2ljY2x1Yi51c2VyLlVzZXISOQoLcGVybWlzc2lvbnMYAiABKAsyJC5tdXNpY2NsdWIucGVybWlzc2lvbnMuUGVybWlzc2lvblNldCIuChlUZWxlZ3JhbVdlYkFwcEF1dGhSZXF1ZXN0EhEKCWluaXRfZGF0YRgBIAEoCTLWAwoLQXV0aFNlcnZpY2USTAoIUmVnaXN0ZXISIy5tdXNpY2NsdWIuYXV0aC5SZWdpc3RlclVzZXJSZXF1ZXN0GhsubXVzaWNjbHViLmF1dGguQXV0aFNlc3Npb24SQQoFTG9naW4SGy5tdXNpY2NsdWIuYXV0aC5DcmVkZW50aWFscxobLm11c2ljY2x1Yi5hdXRoLkF1dGhTZXNzaW9uEkQKB1JlZnJlc2gSHi5tdXNpY2NsdWIuYXV0aC5SZWZyZXNoUmVxdWVzdBoZLm11c2ljY2x1Yi5hdXRoLlRva2VuUGFpchJLCg5HZXRUZ0xvZ2luTGluaxIULm11c2ljY2x1Yi51c2VyLlVzZXIaIy5tdXNpY2NsdWIuYXV0aC5UZ0xvZ2luTGlua1Jlc3BvbnNlEkUKCkdldFByb2ZpbGUSFi5nb29nbGUucHJvdG9idWYuRW1wdHkaHy5tdXNpY2NsdWIuYXV0aC5Qcm9maWxlUmVzcG9uc2USXAoSVGVsZWdyYW1XZWJBcHBBdXRoEikubXVzaWNjbHViLmF1dGguVGVsZWdyYW1XZWJBcHBBdXRoUmVxdWVzdBobLm11c2ljY2x1Yi5hdXRoLkF1dGhTZXNzaW9uQhxaGm11c2ljY2x1YmJvdC9iYWNrZW5kL3Byb3RvYgZwcm90bzM", [file_google_protobuf_empty, file_permissions, file_user]);

/**
 * @generated from message musicclub.auth.Credentials
 */
export type Credentials = Message<"musicclub.auth.Credentials"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message musicclub.auth.Credentials.
 * Use `create(CredentialsSchema)` to create a new message.
 */
export const CredentialsSchema: GenMessage<Credentials> = /*@__PURE__*/
  messageDesc(file_auth, 0);

/**
 * @generated from message musicclub.auth.RegisterUserRequest
 */
export type RegisterUserRequest = Message<"musicclub.auth.RegisterUserRequest"> & {
  /**
   * @generated from field: musicclub.auth.Credentials credentials = 1;
   */
  credentials?: Credentials;

  /**
   * @generated from field: musicclub.user.User profile = 2;
   */
  profile?: User;
};

/**
 * Describes the message musicclub.auth.RegisterUserRequest.
 * Use `create(RegisterUserRequestSchema)` to create a new message.
 */
export const RegisterUserRequestSchema: GenMessage<RegisterUserRequest> = /*@__PURE__*/
  messageDesc(file_auth, 1);

/**
 * @generated from message musicclub.auth.RefreshRequest
 */
export type RefreshRequest = Message<"musicclub.auth.RefreshRequest"> & {
  /**
   * @generated from field: string refresh_token = 1;
   */
  refreshToken: string;
};

/**
 * Describes the message musicclub.auth.RefreshRequest.
 * Use `create(RefreshRequestSchema)` to create a new message.
 */
export const RefreshRequestSchema: GenMessage<RefreshRequest> = /*@__PURE__*/
  messageDesc(file_auth, 2);

/**
 * @generated from message musicclub.auth.TokenPair
 */
export type TokenPair = Message<"musicclub.auth.TokenPair"> & {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * @generated from field: string refresh_token = 2;
   */
  refreshToken: string;
};

/**
 * Describes the message musicclub.auth.TokenPair.
 * Use `create(TokenPairSchema)` to create a new message.
 */
export const TokenPairSchema: GenMessage<TokenPair> = /*@__PURE__*/
  messageDesc(file_auth, 3);

/**
 * @generated from message musicclub.auth.TgLoginLinkResponse
 */
export type TgLoginLinkResponse = Message<"musicclub.auth.TgLoginLinkResponse"> & {
  /**
   * @generated from field: string login_link = 1;
   */
  loginLink: string;
};

/**
 * Describes the message musicclub.auth.TgLoginLinkResponse.
 * Use `create(TgLoginLinkResponseSchema)` to create a new message.
 */
export const TgLoginLinkResponseSchema: GenMessage<TgLoginLinkResponse> = /*@__PURE__*/
  messageDesc(file_auth, 4);

/**
 * @generated from message musicclub.auth.TgLoginRequest
 */
export type TgLoginRequest = Message<"musicclub.auth.TgLoginRequest"> & {
  /**
   * @generated from field: musicclub.user.User user = 1;
   */
  user?: User;

  /**
   * Optional explicit Telegram user id (if provided by the client).
   *
   * @generated from field: uint64 tg_user_id = 2;
   */
  tgUserId: bigint;
};

/**
 * Describes the message musicclub.auth.TgLoginRequest.
 * Use `create(TgLoginRequestSchema)` to create a new message.
 */
export const TgLoginRequestSchema: GenMessage<TgLoginRequest> = /*@__PURE__*/
  messageDesc(file_auth, 5);

/**
 * @generated from message musicclub.auth.AuthSession
 */
export type AuthSession = Message<"musicclub.auth.AuthSession"> & {
  /**
   * JWT token pair.
   *
   * @generated from field: musicclub.auth.TokenPair tokens = 1;
   */
  tokens?: TokenPair;

  /**
   * Token issued-at and expiration (unix seconds).
   *
   * @generated from field: uint64 iat = 2;
   */
  iat: bigint;

  /**
   * @generated from field: uint64 exp = 3;
   */
  exp: bigint;

  /**
   * Whether the user is already a member of the music club chat.
   *
   * @generated from field: bool is_chat_member = 4;
   */
  isChatMember: boolean;

  /**
   * If not a member, link to request manual approval to join the chat.
   *
   * @generated from field: string join_request_url = 5;
   */
  joinRequestUrl: string;

  /**
   * Convenience: current user's profile data.
   *
   * @generated from field: musicclub.user.User profile = 6;
   */
  profile?: User;

  /**
   * Permissions snapshot for the session.
   *
   * @generated from field: musicclub.permissions.PermissionSet permissions = 7;
   */
  permissions?: PermissionSet;
};

/**
 * Describes the message musicclub.auth.AuthSession.
 * Use `create(AuthSessionSchema)` to create a new message.
 */
export const AuthSessionSchema: GenMessage<AuthSession> = /*@__PURE__*/
  messageDesc(file_auth, 6);

/**
 * @generated from message musicclub.auth.ProfileResponse
 */
export type ProfileResponse = Message<"musicclub.auth.ProfileResponse"> & {
  /**
   * @generated from field: musicclub.user.User profile = 1;
   */
  profile?: User;

  /**
   * @generated from field: musicclub.permissions.PermissionSet permissions = 2;
   */
  permissions?: PermissionSet;
};

/**
 * Describes the message musicclub.auth.ProfileResponse.
 * Use `create(ProfileResponseSchema)` to create a new message.
 */
export const ProfileResponseSchema: GenMessage<ProfileResponse> = /*@__PURE__*/
  messageDesc(file_auth, 7);

/**
 * @generated from message musicclub.auth.TelegramWebAppAuthRequest
 */
export type TelegramWebAppAuthRequest = Message<"musicclub.auth.TelegramWebAppAuthRequest"> & {
  /**
   * Raw initData string from Telegram WebApp
   *
   * @generated from field: string init_data = 1;
   */
  initData: string;
};

/**
 * Describes the message musicclub.auth.TelegramWebAppAuthRequest.
 * Use `create(TelegramWebAppAuthRequestSchema)` to create a new message.
 */
export const TelegramWebAppAuthRequestSchema: GenMessage<TelegramWebAppAuthRequest> = /*@__PURE__*/
  messageDesc(file_auth, 8);

/**
 * Authentication and membership gating for the app.
 *
 * @generated from service musicclub.auth.AuthService
 */
export const AuthService: GenService<{
  /**
   * Registers the new user in the system.
   *
   * @generated from rpc musicclub.auth.AuthService.Register
   */
  register: {
    methodKind: "unary";
    input: typeof RegisterUserRequestSchema;
    output: typeof AuthSessionSchema;
  },
  /**
   * Logins the user.
   *
   * @generated from rpc musicclub.auth.AuthService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof CredentialsSchema;
    output: typeof AuthSessionSchema;
  },
  /**
   * Refreshes JWT token pair.
   *
   * @generated from rpc musicclub.auth.AuthService.Refresh
   */
  refresh: {
    methodKind: "unary";
    input: typeof RefreshRequestSchema;
    output: typeof TokenPairSchema;
  },
  /**
   * Generates Telegram url to link account with telegram.
   *
   * @generated from rpc musicclub.auth.AuthService.GetTgLoginLink
   */
  getTgLoginLink: {
    methodKind: "unary";
    input: typeof UserSchema;
    output: typeof TgLoginLinkResponseSchema;
  },
  /**
   * Returns current user profile and permissions for UI gating.
   *
   * @generated from rpc musicclub.auth.AuthService.GetProfile
   */
  getProfile: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof ProfileResponseSchema;
  },
  /**
   * Authenticates user via Telegram WebApp initData.
   *
   * @generated from rpc musicclub.auth.AuthService.TelegramWebAppAuth
   */
  telegramWebAppAuth: {
    methodKind: "unary";
    input: typeof TelegramWebAppAuthRequestSchema;
    output: typeof AuthSessionSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_auth, 0);

