<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <RootNamespace>CuMusicClub.Web</RootNamespace>
        <AssemblyName>CuMusicClub.Web</AssemblyName>
        <SpaRoot>ClientApp\</SpaRoot>
        <OpenApiDocumentsDirectory>./wwwroot/openapi/</OpenApiDocumentsDirectory>
        <OpenApiGenerateDocumentsOptions>--file-name v1</OpenApiGenerateDocumentsOptions>
        <UserSecretsId>a23eb711-3d7c-49a8-a6c6-409a4e03fd21</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Application\Application.csproj"/>
        <ProjectReference Include="..\Infrastructure\Infrastructure.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations"/>
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
        <PackageReference Include="Microsoft.Extensions.ApiDescription.Server">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Scalar.AspNetCore"/>
        <PackageReference Include="Telegram.Bot"/>
    </ItemGroup>

    <ItemGroup>
        <_ContentIncludedByDefault Remove="ClientApp\dist\ClientApp\prerendered-routes.json"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="wwwroot\favicon.ico"/>
    </ItemGroup>

    <Target Name="PublishRunWebpack" AfterTargets="ComputeFilesToPublish" Condition="'$(PublishRunWebpack)' != 'false'">
        <Exec WorkingDirectory="$(SpaRoot)" Command="npm install"/>
        <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build -- --configuration production"/>
        <ItemGroup>
            <DistFiles Include="$(SpaRoot)dist\browser\**;"/>
            <ResolvedFileToPublish Include="@(DistFiles-&gt;'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
                <RelativePath>wwwroot\%(RecursiveDir)%(FileName)%(Extension)</RelativePath>
                <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
                <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
            </ResolvedFileToPublish>
        </ItemGroup>
    </Target>
</Project>
