<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>CuMusicClub.Application</RootNamespace>
        <AssemblyName>CuMusicClub.Application</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Ardalis.GuardClauses"/>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions"/>
        <PackageReference Include="System.IdentityModel.Tokens.Jwt"/>
        <PackageReference Include="Telegram.Bot"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Domain\Domain.csproj"/>
    </ItemGroup>

</Project>
